### ISSUE TITLE
大佬，一直卡在这里怎么办啊？

### ISSUE THREAD

**Issue by thekingofsaltyfish** [FlyAndNotDown/ChatRoom#4]
![image](https://github.com/FlyAndNotDown/ChatRoom/assets/71825302/4edb51ea-ad9b-48d6-b475-edc39f1bc736)

**Comment by kalulas** [comment]
你的server已经启动完毕了。像 README 中描述的那样，启动server后，在另一个命令行窗口启动client即可：
`python3 ./client_start.py`

**Comment by thekingofsaltyfish** [comment]
谢谢！会使用了
